# Generated by Django 4.2.4 on 2023-11-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0002_alter_usuarios_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
