# Generated by Django 4.2.7 on 2023-11-24 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0003_alter_usuarios_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dias_novedades',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='dias_novedades',
            name='novedad',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='fecha_de_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.AddField(
            model_name='novedades',
            name='dias_acumulados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='descripcion',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='tipoNovedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.tiposnovedades'),
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
        migrations.DeleteModel(
            name='Dias_Novedades',
        ),
    ]
